# shadow/tables.py

SLIPPAGE_BPS_BY_REGIME = {
    "HIGH_VOL_CHOP": 12,
    "LOW_VOL_UPTREND": 4,
    "LOW_VOL_DOWNTREND": 4,
}

LATENCY_MS_BY_REGIME = {
    "HIGH_VOL_CHOP": 80,
    "LOW_VOL_UPTREND": 20,
    "LOW_VOL_DOWNTREND": 20,
}

FILL_RATE_BY_REGIME = {
    "HIGH_VOL_CHOP": 0.6,
    "LOW_VOL_UPTREND": 1.0,
    "LOW_VOL_DOWNTREND": 0.9,
}

CONSTRAINT_BLOCK_REGIME = {
    "HIGH_VOL_CHOP": "VOLATILITY_GUARD",
}
