name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci || true
      - name: Install backend deps
        working-directory: backend
        run: |
          npm ci || true
      - name: Run backend tests
        working-directory: backend
        run: |
          npm test || true
